services:
  - type: web
    name: ojt-php-app
    env: php
    plan: free
     rootDir: ojt_web_app
    buildCommand: ""
    startCommand: php -S 0.0.0.0:10000
    envVars:
      - key: DB_HOST
        value: dpg-d4fnncvpmn1nc73f3k1rg-a.singapore-postgres.render.com
      - key: DB_NAME
        value: ojt_system
      - key: DB_USER
        value: ojt_user
      - key: DB_PASS
        value: uIR37XPSCdh0V5xDMxmy03UdfuXYJEPH
    healthCheckPath: /api.php?action=validate_student

